title: Jonathan Pando Ocón, Ph.D.
author: Jonathan Pando Ocón
logo: content/images/profile.png

execute:
  execute_notebooks: force

# Link to other Jupyter Books in the same repository
myst_book_extensions:
  linkcode_resolve: true

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://jpocon.github.io/
  repository_provider: github
  path_to_book: ""
  branch: main

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: custom
